sudo: false
language: python
python:
    - '2.7'
deploy:
    provider: pypi
    user: mwojcikowski
    password:
        secure: Y1+kPOAjQhFZW9N25q8StT5TFvJiUhecTbmpHIlGzlPi/L/RUE8txXXI5e7o4lD0bz5pqDtoKwF8Nas2VQJGS/dE0lkjmsDR/cQdjoSd88BflhxaqlvL6L2fVmIZ2RWXXmrlE6s/Obw1JpMjtzhCGk0ywe306Z1NVkj1VEURIlc=
    distributions: sdist bdist_wheel egg_info
    on:
        tags: true
        repo: oddt/oddt
        branch: master
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda install --yes python=$TRAVIS_PYTHON_VERSION
    - conda env update --name root --file environment.yml
install:
    - pip install .
script: python -c "import oddt"
