name: oddt_env
channels:
- mwojcikowski
- rdkit
dependencies:
- numpydoc
- argparse
- numpy>=1.8
- scipy>=0.13.0
- scikit-learn>=0.13.0
- ffnet>=0.7.1
- joblib>=0.8
- networkx>=1.3
- rdkit
- openbabel
